version: '0.1.{build}'
dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

platform:
    - x64
    - Any CPU

configuration:
    - Debug
    - Release