version: '0.1.{build}'
dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

image: Visual Studio 2017

platform:
    - Any CPU

configuration:
    - Debug
    - Release

install:
    - nuget restore src\code-scanner.sln

test_script:
    - vstest.console /logger:Appveyor %APPVEYOR_BUILD_FOLDER%\src\code-scanner-tests\bin\%CONFIGURATION%\net471\Proegssilb.CodeScanner.Tests.dll